# This is a basic workflow to get started 

name: Simple Manual Workflow - Three Env

on: push
 #workflow_dispatch:
  
jobs:

    DEV: 
    
      runs-on: ubuntu-latest
      environment: DEV
      
      
      steps:
      
        - uses: actions/checkout@v2
        - name: Run a script
          run:
            echo " I'm running a job in the DEV enviornment"
            
    QA:
       
        runs-on: ubuntu-latest
        environment: QA
        needs: DEV 
        
        steps:
          - uses: actions/checkout@v2
          - name: Run a script
            run:
               echo " I'm running a job in the QA enviornment"
            
            
    PROD:
       
        runs-on: ubuntu-latest
        environment: PROD
        needs: QA 
        
        steps:
          - uses: actions/checkout@v2
          - name: Run a script
            run:
               echo " I'm running a job in the PROD enviornment"
            
      
